project:
  type: website
  output-dir: docs

website:
  title: "stpoisci"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - research.qmd
      - Notes.qmd

format:
  html:
    theme: Pulse
    css: styles.css
    link-external-newwindow: true
    toc: true
    toc-title: " "
    callout-appearance: simple

editer: visual

