project:
  type: website
  output-dir: docs

website:
  site-url: "https://www.stpolisci.net/"
  title: "stpolisci"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/about.qmd
        text: About
      - href: cv/cv.qmd
        text: CV
      - href: research/research.qmd
        text: Research
      - href: notes/notes.qmd
        text: Notes

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



