project:
  type: website
  output-dir: docs

website:
  title: "stpolisci"
  google-analytics: "G-PJMBZ1E0ZS"
  page-footer: "Copyright 2024, stpolisci. Powered by [Quarto](https://quarto.org/)"
  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv/cv.qmd
      - text: "Research"
        href: research/research.qmd
      - text: "Notes"
        href: notes/Notes.qmd
    right: 
      # - icon: envelope
      #   href: mailto:sena.tanaka0210@gmail.com
      - icon: github
        href: https://github.com/stpolisci

format:
  html:
    theme: default
    css: styles.css
    link-external-newwindow: true
    toc: true
    toc-title: ""
    callout-appearance: simple

editer: visual

